name: weconnect
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutterfire_ui: ^0.3.3
  firebase_core: ^1.12.0
  get: ^4.6.1
  sizer: ^2.0.15
  firebase_auth: ^3.3.6
  syncfusion_flutter_xlsio: ^19.4.50-beta
  universal_html: ^2.0.8
  flutter_spinkit: ^5.1.0
  cloud_firestore: ^3.1.8
  giff_dialog: ^1.0.1
  shared_preferences: ^2.0.13
  expandable_text: ^2.2.0
  glassmorphism_ui: ^0.2.0
  carousel_slider: ^4.0.0
  timeago: ^3.2.2
  salomon_bottom_bar: ^3.2.0
  material_design_icons_flutter: ^5.0.6595
  animated_text_kit: ^4.2.1
  file_picker: ^4.4.0
  firebase_storage: ^10.2.7
  get_storage: ^2.0.3
  animated_bottom_navigation_bar: ^0.3.2
  focused_menu: ^1.0.5
  avatar_glow: ^2.0.2
  flutter_slidable: ^1.2.0
  image_picker: ^0.8.4+10
  linkwell: ^2.0.6
  url_launcher: ^6.0.20
  intl: ^0.17.0
  like_button: ^2.0.4
  iconsax: ^0.0.8
  google_nav_bar: ^5.0.6
  video_player: ^2.3.0
  flutter_markdown: ^0.6.9+1
  flutter_launcher_icons: ^0.9.2
  flutter_native_splash: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
  flutter_svg: ^1.0.3

flutter_icons:
  android: true
  ios: true
  image_path: "assets/app_icon/logo.png"

flutter_native_splash:
  color: "#FFFFFF"
  image: "assets/app_icon/splash.png"

flutter:
  uses-material-design: true

  assets:
    - assets/app_icon/
    - assets/vectors/
    - assets/gifs/
    - assets/logo/
    - assets/avatars/
    - assets/gallery/
    - assets/colleges/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Black.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
        - asset: assets/fonts/Poppins-ExtraBold.ttf
        - asset: assets/fonts/Poppins-ExtraLight.ttf
        - asset: assets/fonts/Poppins-Light.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-SemiBold.ttf
        - asset: assets/fonts/Poppins-Thin.ttf
          style: italic
