name: weconnect
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  avatar_glow: ^2.0.2
  animated_text_kit: ^4.2.2
  carousel_slider: ^4.1.1
  cloud_firestore: ^4.2.0
  cupertino_icons: ^1.0.5
  expandable_text: ^2.3.0
  file_picker: ^5.2.4
  firebase_auth: ^4.2.1
  firebase_core: ^2.4.0
  firebase_storage: ^11.0.8
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.11.0
  flutter_markdown: ^0.6.10+3
  flutter_native_splash: ^2.2.5
  flutter_slidable: ^2.0.0
  flutter_spinkit: ^5.1.0
  flutter_svg: ^1.1.1+1
  flutterfire_ui: ^0.4.3
  focused_menu: ^1.0.5
  get: ^4.6.5
  get_storage: ^2.0.3
  giff_dialog: ^1.0.1
  iconsax: ^0.0.8
  image_picker: ^0.8.5+3
  intl: ^0.17.0
  like_button: ^2.0.4
  linkwell: ^2.0.6
  lottie: ^2.1.0
  salomon_bottom_bar: ^3.3.1
  shared_preferences: ^2.0.15
  sizer: ^2.0.15
  syncfusion_flutter_xlsio: ^20.2.39-beta
  timeago: ^3.2.2
  universal_html: ^2.0.8
  url_launcher: ^6.1.5
  google_nav_bar: ^5.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1

flutter_icons:
  android: true
  ios: true
  image_path: "assets/app_icon/logo.png"

flutter_native_splash:
  color: "#282A37"
  image: "assets/app_icon/splash.png"

flutter:
  uses-material-design: true

  assets:
    - assets/app_icon/
    - assets/vectors/
    - assets/gifs/
    - assets/logo/
    - assets/avatars/
    - assets/gallery/
    - assets/colleges/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Black.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
        - asset: assets/fonts/Poppins-ExtraBold.ttf
        - asset: assets/fonts/Poppins-ExtraLight.ttf
        - asset: assets/fonts/Poppins-Light.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-SemiBold.ttf
        - asset: assets/fonts/Poppins-Thin.ttf
          style: italic
