// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBtTy_2jZHrXhWau9lWgh_f_fZENWpUEsY',
    appId: '1:247985629491:web:f96f24cdf25685e02ab646',
    messagingSenderId: '247985629491',
    projectId: 'weconnect-f6cb7',
    authDomain: 'weconnect-f6cb7.firebaseapp.com',
    storageBucket: 'weconnect-f6cb7.appspot.com',
    measurementId: 'G-HT9GR904JJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBl1PcNEWJhtVxmQUrdm4-pzbdgTjdZD60',
    appId: '1:247985629491:android:28eba6317708c0252ab646',
    messagingSenderId: '247985629491',
    projectId: 'weconnect-f6cb7',
    storageBucket: 'weconnect-f6cb7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA5ctdkxIW9M9EkhJEnT9vm32YRaUNQkWs',
    appId: '1:247985629491:ios:17def9f199e543102ab646',
    messagingSenderId: '247985629491',
    projectId: 'weconnect-f6cb7',
    storageBucket: 'weconnect-f6cb7.appspot.com',
    iosClientId: '247985629491-ihfktvpidg337rqvsum5t9o7kps9vp5m.apps.googleusercontent.com',
    iosBundleId: 'com.example.weconnect',
  );
}
