// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAeYGjCAtnQ6Fuga8RrGtoRcB-s1EiCoJQ',
    appId: '1:50529742798:web:6ede5225ee6c5bc1a7459f',
    messagingSenderId: '50529742798',
    projectId: 'weconnect-80594',
    authDomain: 'weconnect-80594.firebaseapp.com',
    storageBucket: 'weconnect-80594.appspot.com',
    measurementId: 'G-LLCRNMLP52',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCmrK80H8cG7FB0zjSele_3MOuBKVMWmFg',
    appId: '1:50529742798:android:bd5cd3c1ddb23396a7459f',
    messagingSenderId: '50529742798',
    projectId: 'weconnect-80594',
    storageBucket: 'weconnect-80594.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCWiyo0nIevDuzFn19MVQnqpfiQIRrNyuw',
    appId: '1:50529742798:ios:a54cab309eef1296a7459f',
    messagingSenderId: '50529742798',
    projectId: 'weconnect-80594',
    storageBucket: 'weconnect-80594.appspot.com',
    iosClientId: '50529742798-2j4rb6oj6nvnvns5tc17kaqrups9uedn.apps.googleusercontent.com',
    iosBundleId: 'com.urs.weconnect.portal',
  );
}
